version: '3'
services:

  nginx:
    image: nginx 
    container_name: nginx
    restart: always
    build: 
      context: ./requirements/nginx
      args:
        - SITE_HOSTNAME=${SITE_HOSTNAME}
    ports:
      - "443:443"
    volumes:
      - wp-content:/var/www/html/
    depends_on:
      - wordpress
    
    networks:
      - my-network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-content:/var/lib/mysql/
    networks:
      - my-network

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MY_SQL_HOST=${MY_SQL_HOST}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - PASSWORD_USER=${PASSWORD_USER}
      - EMAIL_USER=${EMAIL_USER}
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-content:/var/www/html/
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis
    restart: always
    build:
      context: ./requirements/bonus/redis
    networks:
      - my-network

  ftp-server:
    image: ftp-server
    container_name: ftp-server
    restart: always
    build:
      context: ./requirements/bonus/ftp-server
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    depends_on:
      - wordpress
    ports:
      - "21:21"
    networks:
      - my-network
    volumes:
      - wp-content:/home/$FTP_USER/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    build: ./requirements/bonus/adminer
    ports:
      - "80:80"
    depends_on:
      - mariadb
    networks:
      - my-network

  jenkins:
    image: jenkins
    container_name: jenkins
    restart: always
    build: ./requirements/bonus/jenkins
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - jenkins:/root/.jenkins/
      - website:/root/.jenkins/workspace/Portfolio/
  
  website:
    image: website
    container_name: resume
    restart: always
    build: ./requirements/bonus/website
    ports:
      - "81:81"
      - "8081:8081"
    networks:
      - my-network
    volumes:
      - website:/var/www/html

volumes:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /home/yojoundi/data/wordpress

  mariadb-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yojoundi/data/mariadb

  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yojoundi/data/website
  jenkins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yojoundi/data/jenkins

networks:
  my-network:
    driver: bridge
