version: '3'
services:

  nginx:
    container_name: nginx
    restart: always
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "81:81"
    volumes:
      - wp-content:/var/www/html/
      - website:/var/www/website/
    depends_on:
      - wordpress
    networks:
      - my-network

  mariadb:
    container_name: mariadb
    restart: always
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-content:/var/lib/mysql/
    networks:
      - my-network

  wordpress:
    container_name: wordpress
    restart: always
    env_file: .env
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MY_SQL_HOST=${MY_SQL_HOST}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - PASSWORD_USER=${PASSWORD_USER}
      - EMAIL_USER=${EMAIL_USER}
    volumes:
      - wp-content:/var/www/html/
    networks:
      - my-network

  redis:
    container_name: redis
    restart: always
    build:
      context: ./requirements/bonus/redis
    networks:
      - my-network

  ftp-server:
    container_name: ftp-server
    restart: always
    build:
      context: ./requirements/bonus/ftp-server
    env_file: .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    depends_on:
      - wordpress
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp-content:/home/ftpuser/

  adminer:
    container_name: adminer
    restart: always
    build: ./requirements/bonus/adminer
    ports:
      - "80:80"
    depends_on:
      - mariadb
    networks:
      - my-network

  jenkins:
    container_name: jenkins
    restart: always
    build: ./requirements/bonus/jenkins
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - website:/root/.jenkins/workspace/Portfolio/

volumes:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /home/yojoundi/data/wordpress

  mariadb-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yojoundi/data/mariadb

  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yojoundi/data/website

networks:
  my-network:
    driver: bridge
