version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-content:/var/www/html/
    depends_on:
      - wordpress
    networks:
      - my-network


  mariadb:
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-content:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress

    depends_on:
      - mariadb
      - redis

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MY_SQL_HOST=${MY_SQL_HOST}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - PASSWORD_USER=${PASSWORD_USER}
      - EMAIL_USER=${EMAIL_USER}

    volumes:
      - wp-content:/var/www/html/
    networks:
      - my-network

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    networks:
      - my-network

  ftp-server:
    container_name: ftp-server
    build:
      context: ./requirements/bonus/ftp-server
    env_file: .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    depends_on:
      - wordpress
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp-content:/home/ftpuser



volumes:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /Users/yojoundi/Desktop/Inception-42/srcs/wp-content
  mariadb-content:

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
