pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/youssefjoundi/Portfolio.git'
            }
        }

        // Add more stages for your build, test, deploy, etc.
    }
}

